on:
  pull_request:
    types: [opened, synchronize]

jobs:
  evaluator_job:
    name: Evaluator Job
    runs-on: ubuntu-18.04
    services:
      mongodb:
        image: mongo
        ports:
          - "27017:27017"
        options: -v ${{ github.workspace }}:/github/workspace
    steps:
      - name: Wait for build to succeed
        uses: betrybe/action-wait-for-check@v2
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: codeclimate
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: actions/checkout@v2
        if: steps.wait-for-build.outputs.conclusion == 'success'
      - name: MongoDB Query Evaluator Step
        uses: betrybe/mongodb-query-evaluator-action@v1
        id: evaluator
        if: steps.wait-for-build.outputs.conclusion == 'success'
        env:
          DBNAME: 'commerce'
        with:
          repository-import-folder: 'assets'
          repository-challenges-folder: 'challenges'
      - name: Store evaluation step
        uses: betrybe/store-evaluation-action@v2
        if: steps.wait-for-build.outputs.conclusion == 'success'
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          environment: production
          pr-number: ${{ github.event.number }}
