on:
  pull_request:
    types: [opened, synchronize]
    
jobs:
  evaluator_job:
    name: Evaluator Job
    runs-on: ubuntu-18.04
    steps:
      - name: Wait for build to succeed
        uses: betrybe/action-wait-for-check@v2
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: codeclimate
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: actions/checkout@v2
        if: steps.wait-for-build.outputs.conclusion == 'success'
      - name: Evaluator step
        id: evaluator
        uses: betrybe/jest-evaluator-action@v6
        if: steps.wait-for-build.outputs.conclusion == 'success'
        with:
          repository-test-name: 'betrybe/sd-0x-stranger-things-backend-tests'
          repository-test-branch: 'master'
        env:
          GITHUB_USER_TEST: ${{ github.actor }} 
      - name: Store evaluation step
        uses: betrybe/store-evaluation-action@v2
        if: steps.wait-for-build.outputs.conclusion == 'success'
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          environment: production
          pr-number: ${{ github.event.number }}
